# Generated by Django 5.1.4 on 2026-03-01 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaLoja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                ("slug", models.SlugField(unique=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("produto", "Produto"), ("software", "Software")],
                        default="produto",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Descrição"
                    ),
                ),
                (
                    "icone",
                    models.CharField(blank=True, max_length=60, verbose_name="Ícone"),
                ),
                ("ordem", models.IntegerField(default=0, verbose_name="Ordem")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Categoria da Loja",
                "verbose_name_plural": "Categorias da Loja",
                "ordering": ["tipo", "ordem", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True, max_length=20, unique=True, verbose_name="Número"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome completo"),
                ),
                (
                    "cpf",
                    models.CharField(blank=True, max_length=14, verbose_name="CPF"),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone"
                    ),
                ),
                (
                    "endereco",
                    models.TextField(blank=True, verbose_name="Endereço de entrega"),
                ),
                ("cep", models.CharField(blank=True, max_length=9, verbose_name="CEP")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("pago", "Pago"),
                            ("enviado", "Enviado"),
                            ("entregue", "Entregue"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Total"
                    ),
                ),
                (
                    "mp_payment_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID Pagamento MP"
                    ),
                ),
                (
                    "mp_status",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Status MP"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome")),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "descricao_curta",
                    models.CharField(max_length=300, verbose_name="Descrição curta"),
                ),
                ("descricao", models.TextField(verbose_name="Descrição completa")),
                (
                    "especificacoes",
                    models.TextField(
                        blank=True,
                        help_text="Uma por linha: Tensão: 220V",
                        verbose_name="Especificações técnicas",
                    ),
                ),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço"
                    ),
                ),
                (
                    "preco_original",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Preço original (riscado)",
                    ),
                ),
                ("estoque", models.IntegerField(default=0, verbose_name="Estoque")),
                (
                    "sku",
                    models.CharField(
                        blank=True, max_length=50, unique=True, verbose_name="SKU"
                    ),
                ),
                (
                    "imagem_capa",
                    models.ImageField(
                        upload_to="loja/produtos/", verbose_name="Imagem principal"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "destaque",
                    models.BooleanField(default=False, verbose_name="Em destaque"),
                ),
                (
                    "parcelas",
                    models.IntegerField(
                        default=6, verbose_name="Parcelas máx. sem juros"
                    ),
                ),
                (
                    "peso_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=6,
                        null=True,
                        verbose_name="Peso (kg)",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="produtos",
                        to="loja.categorialoja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
                "ordering": ["-destaque", "nome"],
            },
        ),
        migrations.CreateModel(
            name="ImagemProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        upload_to="loja/produtos/fotos/", verbose_name="Imagem"
                    ),
                ),
                (
                    "legenda",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Legenda"
                    ),
                ),
                ("ordem", models.IntegerField(default=0, verbose_name="Ordem")),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens",
                        to="loja.produto",
                    ),
                ),
            ],
            options={
                "ordering": ["ordem"],
            },
        ),
        migrations.CreateModel(
            name="Software",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome")),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("tagline", models.CharField(max_length=200, verbose_name="Tagline")),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "funcionalidades",
                    models.TextField(
                        blank=True,
                        help_text="Uma por linha",
                        verbose_name="Funcionalidades",
                    ),
                ),
                (
                    "preco_mensal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Preço mensal",
                    ),
                ),
                (
                    "preco_anual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Preço anual",
                    ),
                ),
                (
                    "preco_vitalicio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Preço vitalício",
                    ),
                ),
                (
                    "imagem_capa",
                    models.ImageField(
                        upload_to="loja/softwares/", verbose_name="Imagem / Screenshot"
                    ),
                ),
                ("demo_url", models.URLField(blank=True, verbose_name="URL Demo")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "destaque",
                    models.BooleanField(default=False, verbose_name="Em destaque"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="softwares",
                        to="loja.categorialoja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Software",
                "verbose_name_plural": "Softwares",
                "ordering": ["-destaque", "nome"],
            },
        ),
        migrations.CreateModel(
            name="ItemPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_item", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "quantidade",
                    models.IntegerField(default=1, verbose_name="Quantidade"),
                ),
                (
                    "preco_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço unitário"
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="loja.pedido",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="loja.produto",
                    ),
                ),
                (
                    "software",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="loja.software",
                    ),
                ),
            ],
        ),
    ]
