# Generated by Django 5.1.4 on 2026-03-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Depoimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                ("empresa", models.CharField(max_length=100, verbose_name="Empresa")),
                (
                    "cargo",
                    models.CharField(blank=True, max_length=100, verbose_name="Cargo"),
                ),
                ("texto", models.TextField(verbose_name="Depoimento")),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="depoimentos/",
                        verbose_name="Foto",
                    ),
                ),
                (
                    "estrelas",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        default=5,
                        verbose_name="Estrelas",
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("ordem", models.IntegerField(default=0, verbose_name="Ordem")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Depoimento",
                "verbose_name_plural": "Depoimentos",
                "ordering": ["ordem", "-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Numero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=80, verbose_name="Título")),
                (
                    "valor",
                    models.CharField(
                        help_text="Ex: 50+, 138kV, 100%",
                        max_length=20,
                        verbose_name="Valor",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=120, verbose_name="Descrição"),
                ),
                (
                    "icone",
                    models.CharField(
                        blank=True,
                        help_text="Classe Heroicons, ex: bolt",
                        max_length=60,
                        verbose_name="Ícone",
                    ),
                ),
                ("ordem", models.IntegerField(default=0, verbose_name="Ordem")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Número / KPI",
                "verbose_name_plural": "Números / KPIs",
                "ordering": ["ordem"],
            },
        ),
        migrations.CreateModel(
            name="Parceiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "logo",
                    models.ImageField(upload_to="parceiros/", verbose_name="Logo"),
                ),
                ("url", models.URLField(blank=True, verbose_name="Site")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("ordem", models.IntegerField(default=0, verbose_name="Ordem")),
            ],
            options={
                "verbose_name": "Parceiro / Cliente",
                "verbose_name_plural": "Parceiros / Clientes",
                "ordering": ["ordem", "nome"],
            },
        ),
    ]
