# Generated by Django 5.1.4 on 2026-03-01 18:52

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaBlog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=80, verbose_name="Nome")),
                ("slug", models.SlugField(unique=True)),
                (
                    "descricao",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Descrição"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.CreateModel(
            name="Artigo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                (
                    "resumo",
                    models.TextField(
                        help_text="Aparece no card e no meta description (SEO)",
                        max_length=400,
                        verbose_name="Resumo",
                    ),
                ),
                (
                    "conteudo",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        verbose_name="Conteúdo"
                    ),
                ),
                (
                    "imagem_capa",
                    models.ImageField(upload_to="blog/", verbose_name="Imagem capa"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("rascunho", "Rascunho"), ("publicado", "Publicado")],
                        default="rascunho",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="Deixe vazio para usar o resumo",
                        max_length=160,
                        verbose_name="Meta Description",
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Meta Keywords"
                    ),
                ),
                (
                    "publicado_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Publicado em"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "visualizacoes",
                    models.IntegerField(default=0, verbose_name="Visualizações"),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artigos",
                        to="blog.categoriablog",
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="blog.tag")),
            ],
            options={
                "verbose_name": "Artigo",
                "verbose_name_plural": "Artigos",
                "ordering": ["-publicado_em"],
            },
        ),
    ]
