# Generated by Django 5.1.4 on 2026-03-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120, verbose_name="Nome")),
                (
                    "empresa",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Empresa"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone / WhatsApp"
                    ),
                ),
                (
                    "assunto",
                    models.CharField(
                        choices=[
                            ("orcamento", "Solicitar Orçamento"),
                            ("projeto_eletrico", "Projeto Elétrico"),
                            ("subestacao", "Subestação"),
                            ("linha_transmissao", "Linha de Transmissão"),
                            ("software", "Software BK"),
                            ("produto", "Produto"),
                            ("parceria", "Parceria Comercial"),
                            ("outro", "Outro"),
                        ],
                        max_length=30,
                        verbose_name="Assunto",
                    ),
                ),
                ("mensagem", models.TextField(verbose_name="Mensagem")),
                (
                    "respondido",
                    models.BooleanField(default=False, verbose_name="Respondido"),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Contato",
                "verbose_name_plural": "Contatos",
                "ordering": ["-criado_em"],
            },
        ),
    ]
