# Generated by Django 5.1.4 on 2026-03-01 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoriaServico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                ("slug", models.SlugField(unique=True)),
                (
                    "icone",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Ícone SVG/Heroicons"
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Descrição"
                    ),
                ),
                ("ordem", models.IntegerField(default=0, verbose_name="Ordem")),
            ],
            options={
                "verbose_name": "Categoria de Serviço",
                "verbose_name_plural": "Categorias de Serviços",
                "ordering": ["ordem"],
            },
        ),
        migrations.CreateModel(
            name="Servico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150, verbose_name="Nome")),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "descricao_curta",
                    models.CharField(max_length=250, verbose_name="Descrição curta"),
                ),
                ("descricao", models.TextField(verbose_name="Descrição completa")),
                (
                    "inclui",
                    models.TextField(
                        blank=True,
                        help_text="Um item por linha",
                        verbose_name="O que inclui",
                    ),
                ),
                (
                    "normas",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Normas aplicáveis"
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="servicos/",
                        verbose_name="Imagem",
                    ),
                ),
                (
                    "destaque",
                    models.BooleanField(default=False, verbose_name="Em destaque"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("ordem", models.IntegerField(default=0, verbose_name="Ordem")),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Meta Description"
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="servicos",
                        to="servicos.categoriaservico",
                    ),
                ),
            ],
            options={
                "verbose_name": "Serviço",
                "verbose_name_plural": "Serviços",
                "ordering": ["categoria__ordem", "ordem", "nome"],
            },
        ),
    ]
