# Generated by Django 5.1.4 on 2026-03-01 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoriaPortfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=80, verbose_name="Nome")),
                ("slug", models.SlugField(unique=True)),
                (
                    "icone",
                    models.CharField(blank=True, max_length=60, verbose_name="Ícone"),
                ),
                ("ordem", models.IntegerField(default=0, verbose_name="Ordem")),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.CreateModel(
            name="ImagemProjeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        upload_to="portfolio/fotos/", verbose_name="Imagem"
                    ),
                ),
                (
                    "legenda",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Legenda"
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagem do Projeto",
                "verbose_name_plural": "Imagens do Projeto",
            },
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "cliente",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Cliente"
                    ),
                ),
                (
                    "local",
                    models.CharField(blank=True, max_length=120, verbose_name="Local"),
                ),
                (
                    "tensao",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("13.8kV", "13,8 kV"),
                            ("34.5kV", "34,5 kV"),
                            ("69kV", "69 kV"),
                            ("138kV", "138 kV"),
                            ("230kV", "230 kV"),
                            ("500kV", "500 kV"),
                            ("outro", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Tensão",
                    ),
                ),
                ("ano", models.IntegerField(blank=True, null=True, verbose_name="Ano")),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "destaques",
                    models.TextField(
                        blank=True,
                        help_text="Um por linha",
                        verbose_name="Destaques técnicos",
                    ),
                ),
                (
                    "imagem_capa",
                    models.ImageField(
                        upload_to="portfolio/", verbose_name="Imagem capa"
                    ),
                ),
                (
                    "destaque",
                    models.BooleanField(default=False, verbose_name="Em destaque"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                ("ordem", models.IntegerField(default=0, verbose_name="Ordem")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projetos",
                        to="portfolio.categoriaportfolio",
                    ),
                ),
                (
                    "imagens",
                    models.ManyToManyField(blank=True, to="portfolio.imagemprojeto"),
                ),
            ],
            options={
                "verbose_name": "Projeto",
                "verbose_name_plural": "Projetos",
                "ordering": ["-destaque", "-ano", "ordem"],
            },
        ),
    ]
